export enum CompanyActionTypes {
  REQUEST_GET_COMPANIES_NOT_ACTIVE = "REQUEST_GET_COMPANIES_NOT_ACTIVE",
  SUCCESS_GET_COMPANIES_NOT_ACTIVE = "SUCCESS_GET_COMPANIES_NOT_ACTIVE",
  FAILED_GET_COMPANIES_NOT_ACTIVE = "FAILED_GET_COMPANIES_NOT_ACTIVE",
  REQUEST_ACTIVATE_COMPANY = "REQUEST_ACTIVATE_COMPANY",
  SUCCESS_ACTIVATE_COMPANY = "SUCCESS_ACTIVATE_COMPANY",
  FAILED_ACTIVATE_COMPANY = "FAILED_ACTIVATE_COMPANY",

}
