export enum ResponsesActionTypes {
  REQUEST_ADD_RESPONSE_SURVEY = "REQUEST_ADD_RESPONSE_SURVEY",
  SUCCESS_ADD_RESPONSE_SURVEY = "SUCCESS_ADD_RESPONSE_SURVEY",
  FAILED_ADD_RESPONSE_SURVEY = "FAILED_ADD_RESPONSE_SURVEY",
  REQUEST_GET_RESPONSES_SURVEY = "REQUEST_GET_RESPONSES_SURVEY",
  SUCCESS_GET_RESPONSES_SURVEY = "SUCCESS_GET_RESPONSES_SURVEY",
  FAILED_GET_RESPONSES_SURVEY = "FAILED_GET_RESPONSES_SURVEY",
}
